# basic .paneru.toml
[options]
focus_follows_mouse = false
mouse_follows_focus = false
animation_speed = 80

[padding]
top = 0
left = 10
right = 10
bottom = 0
[swipe]
continuous = true
[swipe.gesture]
fingers_count = 3
[bindings]
window_focus_west = "ctrl - leftarrow"
window_focus_east = "ctrl - rightarrow"
window_resize = "alt - r"
window_center = "alt - c"
window_fullwidth = "ctrl - f"
window_swap_west = "alt - leftarrow"
window_swap_east = "alt - rightarrow"
